hmrc/professional-subscriptions-frontend

app/controllers/CannotClaimYearSpecificController.scala
app/controllers/WhichSubscriptionController.scala
app/models/ProfessionalBody.scala
app/views/CannotClaimYearSpecificView.scala.html
app/views/WhichSubscriptionView.scala.html
app/views/components/input_autocomplete.scala.html
conf/app.routes
conf/messages.en
test/controllers/CannotClaimYearSpecificControllerSpec.scala
test/controllers/WhichSubscriptionControllerSpec.scala
test/models/ProfessionalBodySpec.scala
test/views/CannotClaimYearSpecificViewSpec.scala

EE-852 - add year specific text function for psubs in autocomplete

---

app/assets/stylesheets/partials/_shame.scss
app/assets/stylesheets/partials/_utilities.scss
app/views/AmountsAlreadyInCodeView.scala.html
app/views/ReEnterAmountsView.scala.html
app/views/TaxYearSelectionView.scala.html
app/views/WhichSubscriptionView.scala.html
app/views/components/input_autocomplete.scala.html
app/views/components/input_tax_year.scala.html
app/views/components/input_yes_no.scala.html

Also tightened up some margins for other combined h1/legend questions

EE-1094 Combined h1 and label/legend

---

app/assets/stylesheets/partials/shame/_focus.scss
app/assets/stylesheets/partials/shame/_palette.scss
app/views/MainTemplate.scala.html
app/views/WhichSubscriptionView.scala.html

Removed reference to map file.
Also updated focus state and palette scss to latest versions.

EE-1108 Moved autocomplete js to page where used

---

conf/professional-bodies.json

**List update**
Energy Institute removed from list as requested

DL-2653 December 2019 List update

---

app/config/Module.scala
app/controllers/DuplicateClaimForOtherYearsController.scala
app/controllers/DuplicateSubscriptionController.scala
app/controllers/EmployerContributionController.scala
app/controllers/ExpensesEmployerPaidController.scala
app/controllers/SummarySubscriptionsController.scala
app/controllers/TaxYearSelectionController.scala
app/models/MongoDateTimeFormats.scala
app/models/UserAnswers.scala
app/repositories/SessionRepository.scala
build.sbt
conf/application.conf
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
project/scaffold.sbt

**Maintenance**
Switched from using play2-reactivemongo to simple-reactivemongo, as well as further dependency updates, and dependency overrides and exclusions that ensure build success.

DL-2680: further dep updates and migrated to simple-reactivemongo

---

conf/application.conf
project/AppDependencies.scala

Changed the order of enabled filters per [the example](https://github.com/hmrc/employee-expenses-frontend/pull/389/commits/a6f3f557e86261308a727afa1126e094943373ac#diff-62ce533313cdad5202810504ca706009) to remove 'Cookie failed message authentication check' warnings. Also raised PRs for [qa](https://github.com/hmrc/app-config-qa/pull/6398), [staging](https://github.com/hmrc/app-config-staging/pull/4493) and [production](https://github.com/hmrc/app-config-production/pull/6052) to remove 'Mongo invalid node status' warnings. 

DL-2862 - Professional Subscriptions - Fix warnings

---

build.sbt
conf/professional-bodies.json
project/AppDependencies.scala
project/build.properties

**New feature**
New list item added Society for British and International Design, with effect from 6 April 2019

DL-2921 March 2020 Update

---

conf/professional-bodies.json

DL-3529
Added "Young Presidents Organisation London, with effect from 6 April 2016" to list of professional bodies

DL-3529 Professional bodies updates for May 2020

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DL-3673 Dependency updates

---

conf/professional-bodies.json

DL-4288
P87 Form changes for Sep 2020
"_Highway Incorporated Engineers Institute of_" --> "_Institute of Highway Engineers_"

DL-4288 P87 updates for September 2020

---

conf/professional-bodies.json

DL-4705 Professional bodies updates for November 2020

---

app/config/FrontendAppConfig.scala
app/views/ErrorTemplate.scala.html
app/views/GovukWrapper.scala.html
app/views/MainTemplate.scala.html
conf/application.conf
project/AppDependencies.scala
test/controllers/TechnicalDifficultiesControllerSpec.scala

DL-5072
- GA removal and integrating with tracking-consent-frontend

DL-5072 Integrating with tracking consent

---

conf/professional-bodies.json

DL-5469 Professional bodies update for April 2021

---

app/controllers/actions/IdentifierAction.scala
build.sbt
project/AppDependencies.scala
project/plugins.sbt

DL-5458
- Upgrading bootstrap to 5.x.x
- Other dependencies updated

DL-5458 Auth-client upgrade

---

app/controllers/ConfirmationCurrentController.scala
app/controllers/ConfirmationCurrentPreviousController.scala
app/controllers/SubmissionController.scala
app/controllers/YourAddressController.scala
app/controllers/YourEmployerController.scala
app/controllers/actions/IdentifierAction.scala
app/services/TaiService.scala
conf/logback.xml
project/AppDependencies.scala
project/plugins.sbt
test/utils/MockPsFormPartialRetriever.scala

DL-5740 Play 2.8

---

conf/professional-bodies.json

DL-6081 added a professional body

---

app/views/ErrorTemplate.scala.html

DL-6093 fixed technical difficulty page bug

---

conf/professional-bodies.json

DL-6143 Professional bodies updates for August 2021

---

conf/professional-bodies.json

DL-6939 Added a professional body

---

test/controllers/TechnicalDifficultiesControllerSpec.scala

DL-7367 - Prof subscriptions fee update

---

app/views/MainTemplate.scala.html

DL-7367 fixed unit tests

---

repository.yaml

DL-7391 Removing leak detection exemption

---

app/views/playComponents/input_autocomplete.scala.html

Added empty field to autocomplete list so that it initially shows as empty.
*Stephen*

DL-9563 - Added autocomplete empty field

---

app/views/DuplicateClaimForOtherYearsView.scala.html
test/controllers/DuplicateClaimForOtherYearsControllerSpec.scala
test/controllers/EmployerContributionControllerSpec.scala
test/controllers/SummarySubscriptionsControllerSpec.scala
test/views/DuplicateClaimForOtherYearsViewSpec.scala

DL-9567 duplicateClaimForOtherYears.scala

---

app/views/RemoveSubscriptionView.scala.html
app/views/playComponents/summary_subscription_table.scala.html
test/controllers/EmployerContributionControllerSpec.scala
test/controllers/RemoveSubscriptionControllerSpec.scala
test/controllers/SummarySubscriptionsControllerSpec.scala
test/views/RemoveSubscriptionViewSpec.scala

DL-9569 - RemoveSubscriptionView

---

app/views/DuplicateClaimYearSelectionView.scala.html
app/views/playComponents/input_checkbox.scala.html
app/views/playComponents/summary_subscription_table.scala.html
test/controllers/CannotClaimEmployerContributionControllerSpec.scala
test/controllers/DuplicateClaimYearSelectionControllerSpec.scala
test/controllers/EmployerContributionControllerSpec.scala
test/controllers/SummarySubscriptionsControllerSpec.scala
test/views/DuplicateClaimYearSelectionViewSpec.scala
test/views/NewViewSpecBase.scala

DL-9568 DuplicateClaimYearSelectionView

---

app/views/DuplicateSubscriptionView.scala.html
app/views/playComponents/submit_button.scala.html
test/controllers/DuplicateSubscriptionControllerSpec.scala
test/views/DuplicateSubscriptionViewSpec.scala

DL-9570 DuplicateSubscriptionView.scala

---

app/views/SelfAssessmentClaimView.scala.html
test/controllers/SelfAssessmentClaimControllerSpec.scala
test/views/SelfAssessmentClaimViewSpec.scala

DL-9571 SelfAssessmentClaimView

---

app/views/UpdateYourEmployerInformationView.scala.html
test/controllers/UpdateYourEmployerInformationControllerSpec.scala
test/views/UpdateYourEmployerInformationViewSpec.scala

DL-9575 - UpdateYourEmployerInformationView

---

app/views/HowYouWillGetYourExpensesCurrentAndPreviousYearView.scala.html
test/controllers/HowYouWillGetYourExpensesControllerSpec.scala
test/views/HowYouWillGetYourExpensesCurrentAndPreviousYearViewSpec.scala

DL-9576 HowYouWillGetYourExpensesCurrentAndPreviousYearView

---

app/controllers/CheckYourAnswersController.scala
app/views/CheckYourAnswersView.scala.html
app/views/playComponents/answer_row.scala.html
app/views/playComponents/answer_section.scala.html
test/controllers/CheckYourAnswersControllerSpec.scala
test/views/CheckYourAnswersViewSpec.scala

DL-9573 CheckYourAnswersView

---

app/views/HowYouWillGetYourExpensesCurrentView.scala.html
test/controllers/HowYouWillGetYourExpensesControllerSpec.scala
test/views/HowYouWillGetYourExpensesCurrentViewSpec.scala

DL-9577 HowYouWillGetYourExpensesCurrentView

---

app/views/YourEmployerView.scala.html
test/controllers/YourEmployerControllerSpec.scala
test/views/YourEmployerViewSpec.scala

DL-9574 yourEmployerView.scala

---

app/views/ConfirmationPreviousView.scala.html
app/views/playComponents/confirmation_footer.scala.html
test/controllers/ConfirmationPreviousControllerSpec.scala
test/views/ConfirmationPreviousViewSpec.scala

DL-9576 confirmationPreviousViewSpec.scala

---

app/views/ConfirmationCurrentView.scala.html
app/views/playComponents/claim_amount_rates_list.scala.html
app/views/playComponents/confirmation_footer.scala.html
test/controllers/ConfirmationCurrentControllerSpec.scala
test/views/ConfirmationCurrentViewSpec.scala

DL-9580 ConfirmationCurrentView

---

app/views/AmountsAlreadyInCodeView.scala.html
test/controllers/AmountsAlreadyInCodeControllerSpec.scala
test/views/AmountsAlreadyInCodeViewSpec.scala

DL-9582 AmountsAlreadyInCodeView

---

app/views/ContactUsView.scala.html
test/controllers/ContactUsControllerSpec.scala
test/views/ContactUsViewSpec.scala

DL-9585 ContactUsView

---

app/views/SessionExpiredView.scala.html
test/controllers/SessionExpiredControllerSpec.scala
test/views/SessionExpiredViewSpec.scala

DL-9588 SessionExpiredView

---

app/views/ErrorTemplate.scala.html
test/controllers/TechnicalDifficultiesControllerSpec.scala

DL-9587 ErrorTemplate

---

app/views/UnauthorisedView.scala.html
test/controllers/UnauthorisedControllerSpec.scala
test/views/UnauthorisedViewSpec.scala

DL-9589 UnauthorisedView

---

app/views/HowYouWillGetYourExpensesCurrentAndPreviousYearView.scala.html

DL-9786 Changed how-you-will-get-your-expenses heading size

---

app/views/ConfirmationCurrentPreviousView.scala.html
app/views/ConfirmationCurrentView.scala.html
app/views/playComponents/claim_amount_rates_list.scala.html
app/views/playComponents/confirmation_footer.scala.html
conf/messages

DL-9787 - Confirmation page improvements

---

app/views/playComponents/confirmation_footer.scala.html

DL-9824 - link new tab update

---

app/views/Layout.scala.html

DL-10540 Adding autocomplete functionality for which subscription page

---

README.md
build.sbt
project/AppDependencies.scala
project/scaffold.sbt
run.sh

DL-9887 update readme

---

conf/professional-bodies.json

DL-11724 correct spelling counselling

---

app/views/CheckYourAnswersView.scala.html
conf/application.conf
project/AppDependencies.scala

DL-11774 remove csp directive

---

project/AppDependencies.scala

DL-12975 update crown logo

---

app/config/FrontendAppConfig.scala
app/controllers/PoliceKickoutController.scala
app/controllers/PoliceKickoutQuestionController.scala
app/forms/PoliceKickoutQuestionFormProvider.scala
app/models/ClaimStatus.scala
app/navigation/Navigator.scala
app/pages/PoliceKickoutPage.scala
app/pages/PoliceKickoutQuestionPage.scala
app/utils/PSubsUtil.scala
app/views/PoliceKickoutQuestionView.scala.html
app/views/PoliceKickoutView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/controllers/PoliceKickoutControllerSpec.scala
test/controllers/PoliceKickoutQuestionControllerSpec.scala
test/forms/PoliceKickoutQuestionFormProviderSpec.scala
test/navigation/NavigatorSpec.scala
test/pages/PoliceKickoutQuestionPageSpec.scala
test/views/PoliceKickoutQuestionViewSpec.scala
test/views/PoliceKickoutViewSpec.scala

New routes:
- `/do-you-work-for-the-met-or-west-yorkshire-police-force/:year/:index`
- `/cannot-claim-met-or-west-yorkshire-police-force`
*Stephen*

DL-12996 - Added police force kickout

---

app/controllers/NoFurtherActionController.scala
app/controllers/PoliceKickoutController.scala
app/models/ClaimStatus.scala
app/views/NoFurtherActionView.scala.html
conf/messages
conf/messages.cy
test/views/NoFurtherActionViewSpec.scala

DL-13080 - Added merged journey link to 'no further action'

---

conf/messages.cy
test/utils/MessagesSpec.scala

DL-13035 adding welsh for merged journey confirmation

---

app/views/ConfirmationCurrentPreviousView.scala.html
app/views/ConfirmationCurrentView.scala.html
app/views/ConfirmationMergedJourneyView.scala.html
app/views/ConfirmationPreviousView.scala.html

Removed backlinks from conf pages

---

conf/application.conf

DL-14104 removing frontend-template-provider config

---

project/AppDependencies.scala
project/plugins.sbt

DL-15074 Dependency changes

---

conf/professional-bodies.json

DL-15271: Updated the list 3 with new changes

---

project/AppDependencies.scala
project/plugins.sbt

DL-15296: rectify the bobby violations
change bootstrap-frontend-play-30 to version 9.7.0 in Appdendencies.scala
Divya

DL-15296: rectify the bobby violations

---

project/AppDependencies.scala
project/plugins.sbt

DL-15296 Rectifying Bobby Violations
Divya

DL-15296 Rectifying Bobby Violations

---

conf/professional-bodies.json

DL-15766: Updated psubs list

---

app/config/FrontendAppConfig.scala
app/controllers/SignOutController.scala
conf/application.conf
test/controllers/SignOutControllerSpec.scala

added bas frontend profile for EE

---

project/AppDependencies.scala
project/plugins.sbt

DL-16920: Dependency changes for bobby violation
